moved install to subcommand

diff --git a/usr/local/bin/stowsh b/usr/local/bin/stowsh
--- a/usr/local/bin/stowsh
+++ b/usr/local/bin/stowsh
@@ -8,9 +8,9 @@ LOG_LEVEL="${LOG_LEVEL:-INFO}";
 DOTFILES_DEPLOY_DIR="${DOTFILES_DEPLOY_DIR:-/mnt/c/Users/cjv28}";
 
 read -r -d '' INSTALL_USAGE <<'EOF'
-stowsh
+stowsh install
 [summary]
-Command for installing your dotfiles.
+stowsh subcommand for installing your dotfiles.
 
 [description]
 Install your dotfiles by cloning them from $DOTFILES_URL, copying the files in the $DOTFILES_PLATFORM of 
@@ -19,13 +19,33 @@ pointing to the files in your $DOTFILES_DEPLOY_DIR.
 
 [usage]
 - View this help message:
-stowsh -h
+stowsh install -h
 
 - Clean up the $HOME/.stowsh folder before executing:
-stowsh -c
+stowsh install -c
 
 - Clean up the $HOME/.stowsh folder after executing:
-stowsh -d
+stowsh install -d
+
+- Execute with a log level of DEBUG:
+LOG_LEVEL=debug stowsh install
+EOF
+
+read -r -d '' STOWSH_USAGE <<'EOF'
+stowsh
+[summary]
+Command for managing your dotfiles.
+
+[description]
+This is a command-line tool for managing dotfiles.
+
+Available subcommands:
+- install (install your dotfiles)
+- git (pass-thru to git on your cloned dotfiles)
+
+[usage]
+- View this help message:
+stowsh -h
 
 - Execute with a log level of DEBUG:
 LOG_LEVEL=debug stowsh
@@ -76,19 +96,7 @@ symlink_to_src() {
     -exec bash -c "symlink_name=\"${dest_dir}/\$(basename {})\"; if [ ! -L \"\${symlink_name}\" ]; then ln -s {} \"\${symlink_name}\"; fi" \;
 }
 
-main() {
-  log_debug "validating required variables";
-
-  if [ ! -d "${HOME}" ]; then
-    log-error "HOME, ${HOME}, does not exist";
-    exit 1;
-  fi
-
-  if [ ! -d "${DOTFILES_DEPLOY_DIR}" ]; then
-    log_error "DOTFILES_DEPLOY_DIR, ${DOTFILES_DEPLOY_DIR}, does not exist";
-    exit 1;
-  fi
-
+install() {
   local clean_post
   local clean_pre
 
@@ -154,6 +162,37 @@ main() {
     log_debug "cleaning after install";
     clean
   fi
+}
+
+main() {
+  log_debug "validating required variables";
+
+  if [ ! -d "${HOME}" ]; then
+    log-error "HOME, ${HOME}, does not exist";
+    exit 1;
+  fi
+
+  if [ ! -d "${DOTFILES_DEPLOY_DIR}" ]; then
+    log_error "DOTFILES_DEPLOY_DIR, ${DOTFILES_DEPLOY_DIR}, does not exist";
+    exit 1;
+  fi
+
+  local subcommand=$1;
+  shift;
+
+  case "${subcommand}" in
+    'install')
+      install "$@";
+      ;;
+    '-h' | '--help')
+      echo "${STOWSH_USAGE}";
+      exit 0;
+      ;;
+    *)
+      log_error "invalid subcommand, ${subcommand}";
+      exit 1;
+      ;;
+  esac
 }
 
 main "$@";
